### ISSUE TITLE
Broken Learning link

### ISSUE THREAD

**Issue by paulleerentveld** [learn-co-curriculum/phase-0-how-to-get-help#6]
When clicking the [Flatiron School's help articles](https://help.learn.co/)] link I get a "Not Found" error page.

**Comment by lizbur10** [comment]
Hi @paulleerentveld ! Thanks for bringing this to our attention. Can you please provide the link to the page in Canvas? 

Thanks!

**Comment by paulleerentveld** [comment]
Just realised its the academyxi version of the page with the old link. The Github version of the link works fine for me. Below is the page with the old link. 
https://academyxi.instructure.com/courses/121/pages/how-to-get-help?module_item_id=15587

**Comment by lizbur10** [comment]
Thanks @paulleerentveld ! This correction has now been made in Canvas 💙
